"""Task Manager — Constants package.  Definitions live in config.py."""

from .config import (
    DEFAULT_LIFECYCLE_PROCESS,
    DEFAULT_PRIORITY,
    DEFAULT_SCORING_RULE,
    ENABLE_NOTIFICATIONS,
    TASKM_MAX_TASKS_PER_PROJECT,
    TASKM_OVERDUE_THRESHOLD_HOURS,
    TASKM_PAGE_SIZE,
)

__all__ = [
    "TASKM_MAX_TASKS_PER_PROJECT",
    "TASKM_PAGE_SIZE",
    "DEFAULT_SCORING_RULE",
    "DEFAULT_LIFECYCLE_PROCESS",
    "ENABLE_NOTIFICATIONS",
    "DEFAULT_PRIORITY",
    "TASKM_OVERDUE_THRESHOLD_HOURS",
]
