# CRM App Configuration
# Loaded by: appos/engine/config.py → load_app_config()

app:
  name: "Customer Relationship Manager"
  short_name: "crm"
  version: "1.0.0"
  description: "CRM application for sales and support teams"
  groups:
    - "sales"
    - "support"
    - "crm_admins"
  db_connected_system: "crm_database"
  theme:
    primary_color: "#3B82F6"
    font_family: "Inter"
  environment: "dev"

  security:
    defaults:
      logic:
        groups:
          - "sales"
          - "support"
          - "crm_admins"
      ui:
        groups:
          - "sales"
          - "support"
          - "crm_admins"
